### ISSUE TITLE
Nothing synced:  file ignored

### ISSUE THREAD

**Issue by ggtd** [syllant/idea-plugin-remotesynchronizer#28]
Hi,

don't know it this is a Issue or bug, or feature. But Can't sync any file. So I try to report it.
Sync always ends with "file ignored". Tried lots of options, nothing helped. 
Using plugin v1.11. BTW the version 1.9 worked better and had more options and menu shortcuts, was more user friendly overall. (my thought)

anyway thanks for the plugin and all effort.

Thanks.

![ssss 2016-08-12 o 15 08 28](https://cloud.githubusercontent.com/assets/7458804/17623119/c07f529a-609e-11e6-948f-3c99a3f7b55b.png)

**Comment by ggtd** [comment]
purchased PyCharm from JetBrains, that solved it. Anyway thanks.

**Comment by syllant** [comment]
Hi Tomáš,

FI:
* The default shortcuts have been removed in 1.10 because of conflicts (cf #16).
* The options have not changed, but they have been moved to work with latest version of the IntelliJ Platform (cf #20).

Regarding you original issue, you can share your mappings  if it happens again, this is the kind of things that should be easy to verify.

Thank you for your report

Sylvain
