### ISSUE TITLE
properties file being ignored.

### ISSUE THREAD

**Issue by imyuyu** [syllant/idea-plugin-remotesynchronizer#32]
hi,
here I come again.

I found a problem，the file is ignored when I synchronize the property file located in classpath:*.properties,but I have nothing to do with the entire module.

I have no problem with other files (such as JAVA files);

please find the screenshot of the configuration below.
![image](https://cloud.githubusercontent.com/assets/5226695/25434084/856d59f6-2abd-11e7-82d6-f0a1db96f61f.png)

module structure
---src
------dbconfig.properties
---WebContent
------WEB-INF

 compiler output
![image](https://cloud.githubusercontent.com/assets/5226695/25434159/d16bc072-2abd-11e7-8548-4f5f80d38ad9.png)

log
2017-04-26 20:21:56 (^) (from E:\IdeaProjects\****\***\src\dbconfig.properties)
1 file ignored

my god,i can't upload pictures.

I am using the version 1.12 of RemoteSynchronizer and Intellij IDEA 2016.1.4

I sincerely hope you can understand what I mean, even though my English is poor.

**Comment by imyuyu** [comment]
I don't know if this is a problem..

**Comment by syllant** [comment]
Hi,

> I sincerely hope you can understand what I mean, even though my English is poor.

No worries, mine is probably not much better and your report is very detailed, thanks for that!

I probably miss some information, because from what I understand, you do not include the directory `E:\IdeaProjects\xxx\src\` in your mappings, so the behavior is OK for me. I only see `$PROJECT_DIR$/xxx/WebContent`, so everything outside will not be synchronized.

Of course, the module structure you gave may be incomplete. What might help would be to provide the exact path of the properties file, and the exact mapping you have configured, just putting 'x' for the directory names you want to hide, but keeping the exact hierarchies.

Thanks

Sylvain

**Comment by imyuyu** [comment]
hi i'm sorry,
because i can't upload pictures.i can only provide text description.please look:
Synchronization mappings:

**tips:**
`$PROJECT_DIR$ = E:\IdeaProjects\xxx_project`

**source_path:**
`$PROJECT_DIR$\pro_xxx_xxx\WebContent = E:\IdeaProjects\xxx_project\pro_xxx_xxx\WebContent `
**target path:**
`$PROJECT_DIR$\..\..\xxx\xxx\xxx\xx = E:\xxx\xxx\xxx\xx`

my module is web project，I have a **source package** called  **"src"** and **WebContent** directory，WebContent is my Web Resource Directory.There are multiple JAVA files and multiple properties files under the source package such as dbconfig.properties. my source package files compiled to `WebContent/WEB-INf/classes/` under.

I can synchronize the java file directly in the **src** directory but cannot synchronize the properties file

I don't know why I can't upload pictures,ah geez....If you need more detailed information, please let me know,i will try to upload pictures!

Tks

Martin

**Comment by syllant** [comment]
Martin,

Here, you ask the plugin to synchronize everything from `E:\IdeaProjects\xxx_project\pro_xxx_xxx\WebContent` to `E:\xxx\xxx\xxx\xx`. It is expected that any class in `E:\IdeaProjects\xxx_project\pro_xxx_xxx\WebContent\WEB-INF\classes` will be copied. And it is expected that files in `E:\IdeaProjects\xxx_project\pro_xxx_xxx\src` will NOT be copied since they are not in the scope.

You have to change your mappings to ensure the files you want to copy are included in the source directories.

Note that for there is something special for Java classes: when you synchronize a source file (`.java`), actually this is the corresponding class file which is synchronized. This is why your synchronization works for class files whereas your source files are not in the source directory `E:\IdeaProjects\xxx_project\pro_xxx_xxx\WebContent`.

Hope it clarifies.

Thanks

Sylvain

**Comment by imyuyu** [comment]
hi
I think I know what you mean,now I added a mapping,It is like this:

**source_path:**
`E:\IdeaProjects\xxx_project\pro_xxx_xxx\src`

**target path:**
`E:\xxx\xxx\xxx\xx\WEB-INF\classes`

Now  the property files can be synchronized！Everything is normal!

Thanks again for your help! I think you can turn off the issue，It's my fault.

Martin

**Comment by imyuyu** [comment]
However if you don't mind,I think you can consider updating this feature. Since all the contents of the source package have been compiled to the` WebContent/WEB_INF/classes`, then why can not be synchronized directly?and you have already done the mapping for the JAVA file to class file, so I think you just need to change the rules, can map the property file under the source package to the properties file in the compiled path to synchronize

eg.
`src/Arrays.java -> WebContent/WEB-INF/classes/Arrays.class`

`src/dbconfig.properties -> WebContent/WEB-INF/classes/dbconfig.properties `

**Comment by syllant** [comment]
You're probably right, all resources belonging to source directories could benefit from this behavior, and not only Java sources, although there would be some challenges to address (e.g. should the source file be also synchronized?). However, it is unlikely I change that soon since this plugin is not under active development.

Thank you

Sylvain
