### ISSUE TITLE
doc issue: how to config the remote connection

### ISSUE THREAD

**Issue by igilbert** [syllant/idea-plugin-remotesynchronizer#36]
no words on how to config the remote connection! Thus cannot figure out how to use it at all.
does it depend on assumed functionality of idea itself? Does it support the idea community version?

**Comment by syllant** [comment]
> no words on how to config the remote connection
Maybe because there is nothing to say?

You don't configure any "connection". This plugin just copies files from one directory to another directory using the file system. As long as your remote location is accessible using a file path, this works. If you want to use SSH, FTP or an other protocol, this plugin is not for you.
